SELECT ED.ID, COALESCE(C.CNT,0) AS CHILD_COUNT
FROM ECOLI_DATA ED LEFT OUTER JOIN
    (SELECT PARENT_ID, COUNT(PARENT_ID) AS CNT
    FROM ECOLI_DATA 
    GROUP BY PARENT_ID) C
ON ED.ID = C.PARENT_ID
ORDER BY ED.ID
