-- 코드를 입력하세요
SELECT IO.ANIMAL_ID, IO.NAME FROM
    (SELECT I.ANIMAL_ID, I.NAME, O.DATETIME - I.DATETIME AS DUR FROM
    ANIMAL_INS I JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DUR DESC) IO
LIMIT 2

;

