-- 코드를 작성해주세요


SELECT 
    RANKING.ID AS ID,
    CASE
        WHEN RANKING.PERCENTAGE <= 25 THEN 'CRITICAL'
        WHEN RANKING.PERCENTAGE <= 50 THEN 'HIGH'
        WHEN RANKING.PERCENTAGE <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM
(
    SELECT  ED.ID,
    (RANK() OVER (ORDER BY ED.SIZE_OF_COLONY DESC)) * 100/CNT.NUM_CNT AS PERCENTAGE
    FROM ECOLI_DATA ED
    JOIN (
        SELECT COUNT(*) AS NUM_CNT
        FROM ECOLI_DATA
    ) CNT
) RANKING
ORDER BY RANKING.ID