SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, A.SC AS SCORE FROM
REST_INFO I JOIN
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SC
FROM REST_REVIEW
GROUP BY REST_ID) A
ON I.REST_ID = A.REST_ID
WHERE I.ADDRESS LIKE '서울%'
ORDER BY A.SC DESC, I.FAVORITES DESC