-- 코드를 입력하세요

-- COUNT(DISTINCT UI.USER_ID) / COUNT(DISTINCT OS.USER_ID)
SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH,
COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT OS.USER_ID) / (
    SELECT COUNT(DISTINCT UI.USER_ID)
    FROM USER_INFO UI
    WHERE YEAR(UI.JOINED) = '2021'
), 1) AS PURCHASED_RATIO
FROM
USER_INFO UI 
LEFT JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE YEAR(UI.JOINED) = '2021'
AND YEAR(OS.SALES_DATE) IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
;