SELECT HF.HISTORY_ID, 
       FLOOR(HF.FEE * ((100 - COALESCE(P.DISCOUNT_RATE, 0)) / 100)) AS FEE
FROM (
    SELECT HH.HISTORY_ID, 
           HH.DURATION * C.DAILY_FEE AS FEE, 
           HH.DURATION_TYPE, 
           C.CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN (
        SELECT DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION, -- DATEDIFF 사용
               H.HISTORY_ID, 
               H.CAR_ID,
               CASE 
                   WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                   WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                   WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
                   ELSE NULL -- 7일 미만의 경우 NULL
               END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ) HH ON C.CAR_ID = HH.CAR_ID
    WHERE C.CAR_TYPE = '트럭' -- 트럭 필터 추가
) HF
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON HF.DURATION_TYPE = P.DURATION_TYPE 
   AND HF.CAR_TYPE = P.CAR_TYPE
ORDER BY FEE DESC, HF.HISTORY_ID DESC;
