-- 코드를 입력하세요
SELECT 
A.APNT_NO AS APNT_NO,
P.PT_NAME AS PT_NAME,
P.PT_NO AS PT_NO,
D.MCDP_CD AS MCDP_CD,
D.DR_NAME AS DR_NAME,
A.APNT_YMD AS APNT_YMD
FROM
PATIENT P JOIN APPOINTMENT A
ON P.PT_NO = A.PT_NO
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
ORDER BY APNT_YMD
;
