-- 코드를 작성해주세요
SELECT CHILD.ID AS ID, CHILD.GENOTYPE AS GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE FROM
ECOLI_DATA CHILD
JOIN ECOLI_DATA PARENT
ON CHILD.PARENT_ID = PARENT.ID
WHERE (PARENT.GENOTYPE ^ CHILD.GENOTYPE) & PARENT.GENOTYPE = 0
ORDER BY ID
;