SELECT MONTH(RH.START_DATE) AS MONTH, RH.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
WHERE RH.CAR_ID IN
    (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE MONTH(H.START_DATE) IN (8, 9, 10) AND YEAR(H.START_DATE) = 2022
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)
AND MONTH(RH.START_DATE) IN (8,9,10) AND YEAR(RH.START_DATE) = 2022
GROUP BY MONTH(RH.START_DATE), RH.CAR_ID
ORDER BY MONTH, CAR_ID DESC;
