-- 코드를 작성해주세요
SELECT 
    MAX_SIZE.YEAR AS YEAR,
    CASE 
        WHEN ED.SIZE_OF_COLONY - MAX_SIZE.MAXSIZE > 0 THEN ED.SIZE_OF_COLONY - MAX_SIZE.MAXSIZE
        ELSE MAX_SIZE.MAXSIZE - ED.SIZE_OF_COLONY
    END AS YEAR_DEV,
    ED.ID AS ID
FROM
ECOLI_DATA ED JOIN

(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXSIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) MAX_SIZE
ON YEAR(ED.DIFFERENTIATION_DATE) = MAX_SIZE.YEAR
ORDER BY MAX_SIZE.YEAR, YEAR_DEV

