SELECT IDLEN.ID, FNINFO.FISH_NAME, IDLEN.LENGTH FROM (
    (SELECT FISHINFO.ID AS ID, ML.MAXLEN AS LENGTH, ML.FISH_TYPE AS FISH_TYPE FROM
    FISH_INFO FISHINFO JOIN (
        SELECT FI.FISH_TYPE, MAX(LENGTH) AS MAXLEN FROM 
        FISH_INFO FI JOIN FISH_NAME_INFO FN
        ON FI.FISH_TYPE = FN.FISH_TYPE
        GROUP BY FISH_TYPE
    ) ML
    ON FISHINFO.FISH_TYPE = ML.FISH_TYPE
    WHERE FISHINFO.LENGTH = ML.MAXLEN
    ) IDLEN
    JOIN FISH_NAME_INFO FNINFO
    ON IDLEN.FISH_TYPE = FNINFO.FISH_TYPE
)
ORDER BY IDLEN.ID;
    