-- 코드를 작성해주세요
SELECT DEPT.DEPT_ID, DEPT.DEPT_NAME_EN, ROUND(AVG(EMP.SAL)) AS AVG_SAL 
FROM HR_EMPLOYEES EMP 
JOIN HR_DEPARTMENT DEPT
ON EMP.DEPT_ID = DEPT.DEPT_ID
GROUP BY DEPT.DEPT_ID, DEPT.DEPT_NAME_EN
ORDER BY AVG_SAL DESC
;