SELECT COUNT(*) AS FISH_COUNT, MAX(A.LEN) AS MAX_LENGTH, A.FISH_TYPE
FROM
    (SELECT FI.FISH_TYPE,
        CASE 
            WHEN COALESCE(FI.LENGTH, 0) <= 10 THEN 10
            ELSE FI.LENGTH 
        END AS LEN
    FROM FISH_INFO FI) A
GROUP BY A.FISH_TYPE
HAVING AVG(A.LEN) >= 33
ORDER BY A.FISH_TYPE
;

    
